services:
  db:
    image: postgres:16-alpine
    container_name: 'star_burger_db'
    volumes:
    - db_data:/var/lib/postgresql/data
    env_file: ./star_burger/.env
    restart: always
    ports:
      - "5432:5432"
  
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: 'star_burger_frontend'
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
    volumes:
      - ./bundles:/star_burger/bundles
      - ./bundles-src:/star_burger/bundles-src
    restart: always
  
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: 'star_burger_backend'
    command: >
        bash -c "python manage.py collectstatic --noinput
        && gunicorn -w 3 -b 0.0.0.0:8000 star_burger.wsgi:application"
    volumes:
      - ./static:/star_burger/static
      - ./media:/star_burger/media
      - ./assets:/star_burger/assets
      - ./bundles:/star_burger/bundles
    ports:  
      - "127.0.0.1:8000:8000"
    depends_on:
      - frontend
      - db
    restart: always

volumes:
  db_data:
  media:
  bundles: 
